맵과셋
Altu-Bitu-3/Altu-Bitu-JungDaso pull request #2
Opened 2022-09-11 16:48 UTC by dasoya

#### 내용 & 질문
> 제출합니다!

#### <기존 제출>
> 문제 번호  10757, 11723, 2910, 7785

2022-09-11 18:30 UTC, dooli1971039 requested changes
**p1. 10757 코드 리뷰 완료**
안녕하세요 다소님~
전반적으로 뒤에서부터 한자리씩 더해나가는 과정은 정말 잘 구현해주셨습니다!
다만 이 문제를 구현하는 과정에서 굳이 map을 사용해야할까요...? 
(필수 문제의 경우, 과제가 나간 주차의 주제와 무관하게 선정됩니다! 꼭 맵과 셋을 써야 하는게 아니에요ㅠㅠ😂)
이 부분 수정하시고 저 다시 불러주세요~~

2022-09-11 18:30 UTC, dooli1971039 commented on 09월 06일 - 맵과 셋/10757.cpp
> +
p2. c++에는 swap() 함수가 있답니다~ 이 함수를 사용하면 좋을 것 같습니다.😉

2022-09-11 22:54 UTC, dasoya commented
> **p1. 10757 코드 리뷰 완료** 안녕하세요 다소님~ 전반적으로 뒤에서부터 한자리씩 더해나가는 과정은 정말 잘 구현해주셨습니다! 다만 이 문제를 구현하는 과정에서 굳이 map을 사용해야할까요...? (필수 문제의 경우, 과제가 나간 주차의 주제와 무관하게 선정됩니다! 꼭 맵과 셋을 써야 하는게 아니에요ㅠㅠ😂) 이 부분 수정하시고 저 다시 불러주세요~~

안녕하세요. 먼저 리뷰 감사합니다. map을 사용하지 않는다면 vector<pair<int,int>> 사용이 필요한 걸까요? 어떤 식으로 수정해야할 지 모르겠어서 질문드립니다.

2022-09-12 00:50 UTC, dooli1971039 commented
map을 사용하신 이유가, 첫번째 인자에는 인덱스, 두번째 인자에는 문자열에서 해당 위치의 숫자를 저장하시기 위함일까요?
첫번째 인자를 그저 인덱스로서 사용한다면, vector나, string을 사용하셔도 될 것 같습니다. 만약 벡터를 쓰신다면, 39번째 줄 부근에서는 이런식으로 적을 수 있겠지요.
```
vector<int> arr1;
for(int i=A.length();i>=0);i--){
    arr1.push_back(A[i]);
}
```
이렇게 쓴다면, 벡터에는 입력받은 문자열이 거꾸로 들어가겠죠? (1234를 입력받았다면, 4321이 벡터에 저장되었을 것)
그럼 이러한 벡터 2개를 add 함수에서 인덱스 0부터 더할 수 있을 거에요. (물론, 두 문자열의 길이가 다르다거나하는 상황에 대한 처리가 필요합니다.)

main에서 따로 처리를 해주지 않고, 바로 add함수에 string A, string B를 넘겨버린다면, 문자열의 뒤에서부터(==1의자리부터) 바로 더할 수도 있을 것 같네요.

2022-09-12 04:34 UTC, dbswn approved these changes
**P3 2910 코드리뷰 완료**
안녕하세요 다소님 😄😄 코드도 깔끔하고 주석도 잘 작성해주셔서 리뷰 드리기 너무 좋았습니다!!!

간단한 코멘트 달았으니, 확인 부탁 드립니다 !수정하신 부분 있으시면 리뷰어로 불러주셔도 좋습니다! 수고 많으셨습니다.감사합니다. 🤗🤗

2022-09-12 04:34 UTC, dbswn commented on 09월 06일 - 맵과 셋/2910.cpp
> +    }
P3
map을 vector로 변경할 때 for-each를 통해 각 항목을 직접 삽입해주셨네요! 조금 더 간단한 방법으로는 vector의 생성자를 사용할 수도 있답니다!
벡터로 바꾸고 싶은 map의 시작과 끝에서 반복자를 가져와 vector 클래스의 범위 생성자에 전달해주면 벡터가 생성됩니다~!
vector<pair<int, int>> vec(count.begin(), count.end());

2022-09-12 04:34 UTC, dbswn commented on 09월 06일 - 맵과 셋/2910.cpp
> +    return A.first > B.first; // 빈도 높은 순
P3
비교 정렬 함수 사용 시, 가독성을 위해 같지 않을 경우에 대한 조건을 먼저 처리 하는 것을 권장해요! 비교하는 조건이 많아질 수록 같은 경우를 먼저 비교하고다음 조건으로 넘어가면 return의 위치가 조건과 멀어져 코드를 한 번에 파악하기 어렵답니다~! -> 국영수 문제 샘플코드를 참고해보세요!

2022-09-12 07:22 UTC, jaeseo222 reviewed
**P3. 7785 코드 리뷰 완료**

안녕하세요 다소님 😄😄 알맞은 로직으로 잘 풀어주셔서 리뷰 드리기 너무 좋았습니다!
나중에, 코드가 길어졌을 땐 주석으로 보충 설명 해주셔도 좋을 것 같습니다.🎆🎆

간단한 코멘트 달았으니, 확인 부탁 드립니다 !
**수정하신 부분 있으시면 리뷰어로 불러주셔도 좋습니다!** 수고 많으셨습니다.
수고 많으셨습니다. 감사합니다. 🤗🤗

2022-09-12 07:22 UTC, jaeseo222 commented on 09월 06일 - 맵과 셋/7785.cpp
> +        }
p3. **map**을 사용하여 잘 풀어주셨네요!!! 🎆🎆
map은 key값을 중복 없이 저장하여, 직원들의 이름을 구분하기 위한 자료형으로 아주 적합하죠.😉
다만, **회사에 없는 사람들까지 map에 저장해줄 필요가 있을까요??** 회사에 있는 사람만 출력해 줄 텐데 말이죠!

이렇게 된다면, 밑에 있는 작업에서의 **결과**와 동일하게 되겠어요! 그럼 작업을 거치지 않아도 되지 않을까요??
```
for(auto& iter : m){

        if(iter.second == 1)
            arr.push_back(iter.first);

    }
```

2022-09-12 07:22 UTC, jaeseo222 commented on 09월 06일 - 맵과 셋/7785.cpp
> +    }
p3. 역순으로 출력해주기 위해, **역으로** 정렬을 잘 구현해주셨네요!!😍
이 방법도 너무 좋고, **역방향 반복자**로도 역순환이 가능합니다!
한번 찾아 봐주셔도 좋을 것 같습니다.🤗

2022-09-12 11:16 UTC, Dong-droid commented
11723 코드 리뷰 완료
너무 잘 푸셨네요!!
이 문제를 푸는 방법은 여러가지(배열, 비트마스킹)이 있는데 그것도 나중에 풀이를 한 번 보시는 것도 좋을 것 같습니다.
수고하셨습니다!

2022-09-26 13:23 UTC, dasoya commented
@dooli1971039 
수정했습니다. 다시 한번 확인 부탁드려요. 감사합니다!

2022-09-26 14:11 UTC, dooli1971039 approved these changes

2022-09-26 14:11 UTC, dooli1971039 commented
10757 확인했습니다! 정말 수고하셨어요!!👍👍

2022-09-27 05:46 UTC, merged